language: generic
sudo: required
python: 2.7

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.1

before_install:
  # Uninstall existing Homebrew installation
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --force

  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - rm -rf /Users/travis/.nvm
  - rm -rf /etc/profile.d/travis-nvm.sh

  # Fix https://github.com/travis-ci/travis-ci/issues/6307
  - rvm get stable

script:
  # Test setup script
  - ./setup -n

  # Check syntax of the Ansible playbooks
  - ./setup -s

  # Run playbooks without installing roles
  - ./setup -q

  # Run idempotence tests for each playbook
  - ./tests/idempotence
