language: generic
sudo: required
python: 2.7

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env: UNINSTALL_HOMEBREW=YES
    - os: osx
      osx_image: xcode9.4
      env: UNINSTALL_HOMEBREW=NO
    - os: osx
      osx_image: xcode10.1
      env: UNINSTALL_HOMEBREW=YES
    - os: osx
      osx_image: xcode10.1
      env: UNINSTALL_HOMEBREW=NO

before_install:

  # Uninstall existing Homebrew installation
  - if [[ "${UNINSTALL_HOMEBREW}" == "YES" ]]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --force; fi

  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - rm -rf /Users/travis/.nvm
  - rm -rf /etc/profile.d/travis-nvm.sh

script:
  # Test setup script
  - ./setup -n

  # Check syntax of the Ansible playbooks
  - ./setup -s

  # Run playbooks without installing roles
  - ./setup -q -i vagrant

  # Run idempotence tests for each playbook
  - ./tests/idempotence
