language: generic
sudo: required
python: 2.7

matrix:
  include:
    - name: "macOS 10.13 (High Sierra) with Xcode 9.4 (uninstall Homebrew)"
      os: osx
      osx_image: xcode9.4
      env: UNINSTALL_HOMEBREW=YES
    - name: "macOS 10.13 (High Sierra) with Xcode 9.4"
      os: osx
      osx_image: xcode9.4
      env: UNINSTALL_HOMEBREW=NO
    - name: "macOS 10.13 (High Sierra) with Xcode 10.1 (uninstall Homebrew)"
      os: osx
      osx_image: xcode10.1
      env: UNINSTALL_HOMEBREW=YES
    - name: "macOS 10.13 (High Sierra) with Xcode 10.1"
      os: osx
      osx_image: xcode10.1
      env: UNINSTALL_HOMEBREW=NO
    - name: "macOS 10.14 (Mojave) with Xcode 10.2 beta (uninstall Homebrew)"
      os: osx
      osx_image: xcode10.2
      env: UNINSTALL_HOMEBREW=YES
    - name: "macOS 10.14 (Mojave) with Xcode 10.2 beta"
      os: osx
      osx_image: xcode10.2
      env: UNINSTALL_HOMEBREW=NO

branches:
  only:
  - master
  - /^feature\/.*$/
  - /^bugfix\/.*$/
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:

  # The default Git on macOS doesn't support protocol version 2 that's enabled on Travis
  # https://stackoverflow.com/questions/53207973/fatal-unknown-value-for-config-protocol-version-2
  - if [[ "${UNINSTALL_HOMEBREW}" == "YES" ]]; then git config --global protocol.version 1; fi

  # Uninstall existing Homebrew installation
  - if [[ "${UNINSTALL_HOMEBREW}" == "YES" ]]; then ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" -- --force; fi

  # Update Homebrew to fix HOMEBREW_LOGS error
  - if [[ "${UNINSTALL_HOMEBREW}" == "NO" ]]; then brew update; fi

  # Cleanup existing NVM installation
  - unset NVM_CD_FLAGS
  - unset NVM_DIR
  - unset NVM_BIN
  - rm -rf /Users/travis/.nvm
  - rm -rf /etc/profile.d/travis-nvm.sh

script:
  # Test setup script
  - ./setup -n

  # Check syntax of the Ansible playbooks
  - ./setup -s

  # Run playbooks without installing roles
  - ./setup -q -i vagrant

  # Run idempotence tests for each playbook
  - ./tests/idempotence
