# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
---
# Do not fix permissions
user_home_fix_permissions: false

# Do not install Hazel automation tool
install_hazel: false

# Do not install Google Drive File Stream
install_gdfs: false

# Do not install Slack
install_slack: false

# Do not install Vagrant or VirtualBox
install_vagrant: false

# Install Hammerspoon automation tool
install_hammerspoon: true

# Install Docker
install_docker: true

# Install Packer
install_packer: true

# Install Certbot
install_certbot: true

# Install nmap
install_nmap: true

# Install Lua programming language
install_lua: true

# Do not install asdf-vm
install_asdf: false

# Install doctl with Homebrew
install_doctl: true

# Install Rust programming language
install_rust: true

# Do not install Ruby and rbenv
install_ruby: false

# Install Python
install_python: false

# Install Go programming language
install_golang: true
