---

- src: https://github.com/markosamuli/ansible-terraform
  name: markosamuli.terraform
- src: https://github.com/markosamuli/ansible-packer
  name: markosamuli.packer
- src: https://github.com/markosamuli/ansible-aws-tools
  name: markosamuli.aws-tools
- src: https://github.com/markosamuli/ansible-nvm
  name: markosamuli.nvm
- src: https://github.com/markosamuli/ansible-gcloud
  name: markosamuli.gcloud
- src: https://github.com/markosamuli/ansible-vagrant
  name: markosamuli.vagrant
- src: https://github.com/markosamuli/ansible-golang
  name: markosamuli.golang
- src: https://github.com/markosamuli/ansible-pyenv
  name: markosamuli.pyenv
