# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#
# Ansible Galaxy roles to install
---

- name: markosamuli.asdf
  src: https://github.com/markosamuli/ansible-asdf
  version: develop
- name: markosamuli.aws-tools
  src: https://github.com/markosamuli/ansible-aws-tools
  version: v1.0.1
- name: markosamuli.gcloud
  version: v2.0.0
- name: markosamuli.golang
  src: https://github.com/markosamuli/ansible-golang
  version: develop
- name: markosamuli.nvm
  src: https://github.com/markosamuli/ansible-nvm
  version: feature/xcode11
- name: markosamuli.packer
  src: https://github.com/markosamuli/ansible-packer
  version: v1.0.0
- name: markosamuli.pyenv
  src: https://github.com/markosamuli/ansible-pyenv
  version: v2.1.0-rc.2
- name: markosamuli.vagrant
  src: https://github.com/markosamuli/ansible-vagrant
  version: v1.0.0
