---
collections:
  - name: geerlingguy.mac
roles:
  - name: elliotweiser.osx-command-line-tools
    version: 2.3.0
  - name: markosamuli.asdf
    version: v1.1.0
  - name: markosamuli.aws_tools
    version: v2.1.0
  - name: markosamuli.gcloud
    src: https://github.com/markosamuli/ansible-gcloud
    version: v2.2.0
  - name: markosamuli.golang
    src: https://github.com/markosamuli/ansible-golang
    version: v3.1.0
  - name: markosamuli.nvm
    version: v1.4.2
  - name: markosamuli.packer
    src: https://github.com/markosamuli/ansible-packer
    version: v1.0.0
  - name: markosamuli.pyenv
    src: https://github.com/markosamuli/ansible-pyenv
    version: v6.1.0
  - name: markosamuli.rust
    src: https://github.com/markosamuli/ansible-rust
    version: master
  - name: markosamuli.vagrant
    src: https://github.com/markosamuli/ansible-vagrant
    version: v1.0.0
  - name: zzet.rbenv
    version: 3.4.7
