---

- name: Editors
  hosts: all
  tags: editors
  tasks:

  - name: Install Visual Studio Code
    homebrew_cask:
      name: visual-studio-code
    tags: vscode

  - name: Install Vim
    homebrew:
      name: vim
    tags: vim

  - name: Install MacVim
    homebrew:
      name: macvim
    tags: vim
