---
- name: Hammerspoon
  hosts: all
  tags: hammerspoon
  tasks:
    - name: Configure Hammerspoon
      when: install_hammerspoon | bool
      block:
        - name: Create ~/.hammerspoon/Spoons directory if it doesn't exist
          file:
            path: ~/.hammerspoon/Spoons
            state: directory
            mode: "0755"

        - name: Download ReloadConfiguration.spoon
          unarchive:
            # yamllint disable-line rule:line-length
            src: https://github.com/Hammerspoon/Spoons/raw/master/Spoons/ReloadConfiguration.spoon.zip
            dest: ~/.hammerspoon/Spoons
            remote_src: true
            creates: ~/.hammerspoon/Spoons/ReloadConfiguration.spoon
            mode: "0755"

        - name: Get ReloadConfiguration.spoon/init.lua checksum
          stat:
            path: ~/.hammerspoon/Spoons/ReloadConfiguration.spoon/init.lua
            checksum_algorithm: sha1
          register: rc_spoon_st

        - name: Check ReloadConfiguration.spoon/init.lua checksum
          assert:
            # yamllint disable-line rule:line-length
            that: "rc_spoon_st.stat.checksum == 'fa06f125578ad79e4b669814dfe0fb24a6c8b1fb'"
