---
- name: Homebrew Cask applications
  hosts: all
  tags: homebrew
  tasks:
    - name: Install Google Chrome
      when: install_chrome | bool
      tags: chrome
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Google Chrome }

    - name: Install Lens (Kubernetes IDE)
      when: install_lens | bool
      tags: lens
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Lens }

    - name: Install Tabby
      when: install_tabby | bool
      tags: tabby
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Tabby }

    - name: Install Keybase
      when: install_keybase | bool
      tags: keybase
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Keybase }

    - name: Install Rectangle
      when: install_rectangle | bool
      tags: rectangle
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Rectangle }

    - name: Install Firefox
      when: install_firefox | bool
      tags: firefox
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Firefox }

    - name: Install Plex
      when: install_plex | bool
      tags: plex
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Plex }

    - name: Install Tuple
      when: install_tuple | bool
      tags: tuple
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Tuple }

    - name: Install Discord
      when: install_discord | bool
      tags: discord
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Discord }

    - name: Install Insomnia
      when: install_insomnia | bool
      tags: insomnia
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Insomnia }

    - name: Install Raycast
      when: install_raycast | bool
      tags: raycast
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Raycast }

    - name: Install CleanShot X
      when: install_cleanshot | bool
      tags: cleanshot
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: CleanShot X, app: cleanshot }

    - name: Install Roon
      when: install_roon | bool
      tags: roon
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Roon }

    - name: Install Google Drive File Stream
      when: install_gdfs | bool
      tags: gdfs
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Google Drive File Stream }

    - name: Install iTerm
      when: install_iterm | bool
      tags: iterm
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: iTerm, app: iterm2 }

    - name: Install Hazel
      when: install_hazel | bool
      tags: hazel
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Hazel }

    - name: Install Docker for Mac
      when: install_docker | bool
      tags: docker
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Docker }

    - name: Visual Studio Code
      tags:
        - editors
        - vscode
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: "Visual Studio Code", app: visual-studio-code }

    - name: JetBrains Toolbox
      when: install_jetbrains_toolbox | bool
      tags: editors
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: JetBrains Toolbox }

    - name: Install Hammerspoon
      when: install_hammerspoon | bool
      tags: hammerspoon
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Hammerspoon }

- name: Homebrew Cask drivers
  hosts: all
  tags: drivers
  tasks:
    - name: Install Logitech drivers
      when: install_logitech_drivers | bool
      tags: logitech
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Logi Options, app: logitech-options }
          - { name: Logitech G HUB, app: logitech-g-hub }

    - name: Install Elgato Stream Deck
      when: install_elgato_stream_deck | bool
      tags: elgato-stream-deck
      import_role:
        name: install_cask_apps
      vars:
        cask_apps:
          - { name: Stream Deck, app: elgato-stream-deck }

- name: Homebrew packages
  hosts: all
  tasks:
    - name: Install tools
      when: install_tools | bool
      tags: tools
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + tools_homebrew_packages }}"

    - name: Install Git
      when: install_git | bool
      tags: git
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + ['git'] }}"

    - name: Install Vim and uninstall MacVim
      when: not install_macvim | bool
      tags: vim
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + ['vim'] }}"
        homebrew_uninstalled_packages: "{{ homebrew_uninstalled_packages + ['macvim'] }}"

    - name: Install MacVim and uninstall Vim
      when: install_macvim | bool
      tags: vim
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + ['macvim'] }}"
        homebrew_uninstalled_packages: "{{ homebrew_uninstalled_packages + ['vim'] }}"

    - name: Install zsh
      when: install_zsh | bool
      tags: zsh
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + ['zsh'] }}"

    - name: Install certbot
      when: install_certbot | bool
      tags: certbot
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + ['certbot'] }}"

    - name: Install nmap
      when: install_nmap | bool
      tags: nmap
      set_fact:
        homebrew_installed_packages: "{{ homebrew_installed_packages + ['nmap'] }}"

    - name: Install Lua
      when: install_lua | bool
      tags: lua
      block:
        - name: Install Lua
          set_fact:
            homebrew_installed_packages: "{{ homebrew_installed_packages + ['lua'] }}"

        - name: Install LuaRocks package manager
          set_fact:
            homebrew_installed_packages: "{{ homebrew_installed_packages + ['luarocks'] }}"

    - name: Install doctl
      when: install_doctl | bool
      tags: doctl
      block:
        - name: Remove doctl asdf plugin
          file:
            path: "{{ ansible_env.HOME }}/.asdf/plugins/doctl"
            state: absent

        - name: Remove doctl asdf installation
          file:
            path: "{{ ansible_env.HOME }}/.asdf/installs/doctl"
            state: absent

        - name: Remove doctl asdf shim
          file:
            path: "{{ ansible_env.HOME }}/.asdf/shims/doctl"
            state: absent

        - name: Install doctl
          set_fact:
            homebrew_installed_packages: "{{ homebrew_installed_packages + ['doctl'] }}"

    - name: Install Terraform
      when: install_terraform | bool
      tags: terraform
      block:
        - name: Install Terraform version manager
          set_fact:
            homebrew_installed_packages: "{{ homebrew_installed_packages + ['tfenv'] }}"

- name: Install and configure Homebrew
  hosts: all
  tags:
    - homebrew
    - drivers
    - lens
    - gdfs
    - iterm
    - tabby
    - rectangle
    - tuple
    - tools
    - shellcheck
    - editors
    - vscode
    - docker
    - hazel
    - git
    - zsh
    - certbot
    - doctl
    - nmap
    - hammerspoon
    - terraform
    - lua
    - chrome
    - elgato-stream-deck
    - roon
    - discord
    - raycast
    - cleanshot
    - insomnia
    - firefox
    - plex
    - keybase
  roles:
    - role: geerlingguy.mac.homebrew
      when: install_homebrew | bool
