---
- name: Lua programming language
  hosts: all
  tags: lua
  tasks:
    - name: Install Packages for Lua
      when: install_lua | bool
      block:
        - name: Install the "luacheck" rock
          luarocks:
            name: luacheck
