---

- name: Python
  hosts: all
  tags:
  - python
  tasks:

  - name: Install Python
    package:
      name: python

  - name: Install virtualenv
    pip:
      name: virtualenv

- name: Python version management
  hosts: all
  become: False
  roles:

  - role: markosamuli.pyenv
    tags: pyenv
