---

- name: Python
  hosts: all
  tasks:

  - name: Install Python
    package:
      name: python

  - name: Install virtualenv
    pip:
      name: virtualenv

- name: Install pyenv
  hosts: all
  roles:

  - role: markosamuli.pyenv
