---
- name: Slack
  hosts: all
  tags: slack
  tasks:
    - name: Install Slack
      when: install_slack | bool
      block:
        - name: Check if Slack has been installed
          stat:
            path: /Applications/Slack.app
          register: slack_st
          changed_when: false

        - name: Install Slack
          community.general.homebrew_cask:
            name: slack
          when: not slack_st.stat.exists
