---

- name: Tools
  hosts: all
  tasks:

  - name: Install wget
    package:
      name: wget

  - name: Install jq command-line JSON processor
    package:
      name: jq

  - name: Install The Silver Searcher code searcing utility
    package:
      name: ag
