---
name: Test

# This workflow is triggered on pushes to the repository.
# yamllint disable rule:truthy
on: [push]
# yamllint enable

jobs:
  build:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Install Ruby 2.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Install Go 1.13.x
        uses: actions/setup-go@v1
        with:
          go-version: "1.13.x"

      - name: Fix Go directory permissions
        run: chmod -R o-rwx /opt/hostedtoolcache/go

      - name: Install pre-commit
        run: |
          pip install virtualenv==16.3.0
          pip install pre-commit
          pre-commit --version

      - name: Install shfmt
        run: |
          export PATH="$PATH:$GOPATH/bin"
          export GO111MODULE=on
          go get mvdan.cc/sh/v3/cmd/shfmt
          shfmt -version
        env:
          GOPATH: /home/runner/go

      - name: Install shellcheck
        run: |
          sudo snap install shellcheck
          shellcheck --version

      - name: Cache pre-commit dependencies
        uses: actions/cache@preview
        with:
          path: ~/.cache/pre-commit/
          # yamllint disable rule:line-length
          key: |
            ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
          # yamllint enable
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      - name: Run pre-commit
        run: |
          export PATH="$PATH:$GOPATH/bin"
          pre-commit run -a
        env:
          GOPATH: /home/runner/go
